### ISSUE TITLE
Sneaky JObject causing SpeckleObject.GetMd5FromObject() to throw SerializationException

### ISSUE THREAD

**Issue by pablothedolphin** [speckleworks/SpeckleStructural#18]
`SpeckleStructuralClasses.StructuralResultBase.Value` is a dictionary of 2 JObject values in the following stream: BCiZ-ggPn

JObject isn't serializable which causes the error. This also has a knock on effect to `SpeckleObject.Scale()` which relies on hashing all properties.

![image](https://user-images.githubusercontent.com/10001744/81286287-b2d44900-9058-11ea-8f9b-9e8f39dbc026.png)

@didimitrie tagging you for your reference

**Comment by daviddekoning** [comment]
@nic-burgers-arup can you have a look? I suspect it is happening somewhere around here: https://github.com/speckleworks/SpeckleStructural/blob/c15efe134a9e9b05365a98a8f027def78397d87e/SpeckleStructuralGSA/ConversionRoutines/NodesAndElements/Structural2DElementMesh.cs#L59

**Comment by nic-burgers-arup** [comment]
Hi @pablothedolphin 

The code relating to results hasn't changed so it's an interesting one ..

Which Speckle server is that stream on?  And can you confirm if you're using GSA 10.0 or 10.1?

Cheers

Nic

**Comment by pablothedolphin** [comment]
@nic-burgers-arup it's actually the stream on hestia that was publicly promoted along side the open source release of SpeckleGSA. I'm not too sure what version of GSA it came from:
https://app.speckle.systems/#/view/BCiZ-ggPn?s=eyJzZXJ2ZXIiOiJodHRwczovL2hlc3RpYS5zcGVja2xlLndvcmtzL2FwaSIsImNhbWVyYSI6eyJ0YXJnZXQiOlsxNi4yMjUzMDkyMjg3NTQ4NzcsMy4xNjE1MDA2ODYyNzMwNzksMTkuODM1ODQ3OTgwNjM1NF0sInBvc2l0aW9uIjpbMzUuNjI1MjI5MzgxOTM1MTcsLTU5LjgzMjkyNzA4ODYxNzQyLDY0LjQxODc4NDM5ODgwODQxXSwicm90YXRpb24iOlswLjk1NDkwMjQyMzg4ODg0LDAuMjQ2MjczOTA4ODI0NjE0MiwwLjE3MDg1NjI5ODc1OTk5NTY0XX0sImdyb3VwcyI6eyJrZXkiOiJBMS52YWx1ZS4yRCBFbGVtZW50IERpc3BsYWNlbWVudF92ZXJ0ZXgudXoifX0

**Comment by pablothedolphin** [comment]
This is now fixed in the 1.1.0 release!
